#!/bin/bash

# export FZF_DEFAULT_COMMAND="fd --type f"
# export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# export FZF_ALT_C_COMMAND="rg -t d . $HOME"
export EDITOR=nvim
export VISUAL=nvim
export ZNAPFOLDER=$HOME/Git
export ASYMPTOTE_DIR=/usr/local/share/systemtap
export COOKIE_FILE=~/.bing-cookies.json
export TEXMFHOME=~/texmf
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
